-- 교수 약력·연구 소개의 옛 DB 찌꺼기 정리 + 연구분야 키워드 (2026-10-09)
-- Supabase SQL Editor 에 붙여넣고 Run. 여러 번 실행해도 결과가 같다.
--  · 'rn'  : 줄바꿈(\r\n)이 글자로 남은 것 → 줄바꿈(<br>)으로 되살렸다.
--             Northwestern·Auburn 처럼 영문자 뒤의 rn 은 건드리지 않았다.
--  · U+F0FC : 워드 Wingdings 글머리표가 그대로 넘어온 것 → <ul><li> 목록으로 되살림.
--  · 주요 논문이 한 덩어리였던 경우 논문별로 끊어 상세 페이지가 번호 목록으로 그릴 수 있게 했다.
-- 본문 정리 11명 12개 항목 · 키워드 18명.

-- ── 약력·연구 소개 본문 ──
update faculty set
      bio_ko = '<h3>학력</h3><ul><li>서강대학교 공학사(1986)</li><li>University of Tsukuba 공학석사(1989)</li><li>University of Tsukuba 공학박사(1993)</li></ul><h3>경력</h3><ul><li>서강대학교 화공생명공학과 교수 (1994~현재)</li><li>미국 Cornell 대학과 일본 동경공업대학 방문교수</li><li>한국공업화학회 편집이사 및 재무이사</li><li>한국고분자학회 평이사</li><li>에너지기술평가원 고급에너지 인력양성사업 단장</li></ul><h3>주요 논문</h3><p>Ga-Eun Lee, Joo Hwan Kim, Jinyoung Kim, Hyun-Seok Cho, Simon MoonGeun Jung, Yuichiro Hayashi, Toshiaki Ito, Kohei Yamaguchi, Yuta Saegusa, Hideaki Takahashi, Hiroshi Sato, Tsutomu Miyasaka, Gyu Min Kim, Se Young Oh, "Interfacial engineering with a carbonyl-functionalized truxene self-assembled monolayer for high efficiency and stable NiOX-based perovskite solar cells." Chemical Engineering Journal (2026): 176106.</p><p>Jinyoung Kim, Joo Hwan Kim, Hyun-Seok Cho, Gyu Min Kim, Se Young Oh, "Mechanochemical All-in-Powder Strategy with Intrinsic Additive Incorporation for High-Efficiency and Durable Perovskite Solar Cells" Small (2025), 21.52: e09799.</p><p>Seri Lee, Gyu Min Kim, Tsutomu Miyasaka, Dong-Il Won, Se Young Oh, "Ge-doped Sn-Pb assisted by MACl triple metal cation perovskite solar cells with high open-circuit voltage" Chemical Engineering Journal (2024), 488: 150817.</p><p>Chan Hyuk Ji, Seon-ju Lee, Se-Young Oh, "P3HT-based visible-light organic photodetectors using PEI/PAA multilayers as a p-type buffer layer", RSC advances (2019) 9.64: 37180-37187.</p><p>Seong Bin Lim, Chan Hyuk Ji, Il Soo Oh, Se-Young Oh, "Reduced leakage current and improved performance of an organic photodetector using an ytterbium cathode interlayer", Journal of Materials Chemistry C (2016) 4.22: 4920-4926.</p>'
  where name_ko = '오세용';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>서강대학교 공학사 (1995)</li><li>서강대학교 공학석사(1997)</li><li>서강대학교 공학박사(2003)</li></ul><h3>경력</h3><ul><li>Postdoctoral fellow (Northwestern University, 2004-2006)</li><li>Visiting Professor (Auburn University, 2012)</li></ul><h3>주요 논문</h3><p>Myeong-Jun Lee, Eun-Sol Lee, Tae-Hwan Kim, Ju-Won Jeon, YongTae Kim, Byung-Keun Oh, “Detection of thioredoxin-1 using ultra-sensitive ELISA with enzyme-encapsulated human serum albumin nanoparticle”, Nano Convergence 6 (2019) 1-7.</p><p>Jinho Yoon, Taek Lee, Jinhee Jo, Byung-Keun Oh, Jeong-Woo Choi, “Electrochemical H2O2 biosensor composed of myoglobin on MoS2 nanoparticle-graphene oxide hybrid structure”, Biosensors and Bioelectronics 93 (2017) 14-20.</p><p>Jin-Ha Choi, Hai-Jin Hwang, Seung Won Shin, Jeong-Woo Choi, Soong Ho Um, Byung-Keun Oh, “A novel albumin nanocomplex containing both small interfering RNA and gold nanorods for synergetic anticancer therapy” Nanoscale 7 (2015) 9229-9237.</p><p>Jin-Ha Choi, Han Kim, Jae-Hak Choi, Jeong-Woo Choi, Byung-Keun Oh. “Signal Enhancement of Silicon Nanowire-Based Biosensor for Detection of Matrix Metalloproteinase-2 Using DNA-Au Nanoparticle Complexes” ACS applied materials &amp; interfaces 5 (2013) 12023-12028.</p><p>Jin Ha Choi, Hyun Soo Kim, Jeong-Woo Choi, Jong Wook Hong, Young-Kee Kim, Byung-Keun Oh, “A novel Au-nanoparticle biosensor for the rapid and simple detection of PSA using a sequence-specific peptide cleavage reaction” Biosensors and Bioelectronics 49 (2013) 415-419.</p>'
  where name_ko = '오병근';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>서울대학교 공학사 (2001)</li><li>서울대학교 공학박사(2006)</li></ul><h3>경력</h3><ul><li>Director, Institute of Integrated Biotechnology, Sogang University (2019-present)</li><li>Professor, Department of Chemical and Biomolecular Engineering, Sogang University (2017-present)</li><li>Trustee of the Korean Institute of Chemical Engineers (2016-present)</li><li>Academic board of the Koreans BioChip Society (2016-present)</li><li>Editor of Journal (NICE) from The Korean Institute of Chemical Engineers (2016-present)</li><li>Editorial Board Member, Scientific Reports (Nature Publishing Group) (2015-present)</li><li>Chair, Department of Chemical and Biomolecular Engineering, Sogang University (2017-2019)</li><li>Visiting Scholar, University of California at Berkeley (2014-2015)</li></ul><h3>주요 논문</h3><p>Yuseung Jo et al., Inner membrane-bound gold nanoparticles as efficient electron transfer mediators for enhanced mitochondrial electron transport chain activity, Nano Letters (2022)</p><p>Keumrai Whang et al., Direct and Precise Determination of Volumetric Mass Transfer Coefficient of Carbon Monoxide for Miniaturized Gas-liquid Reactors via Sensitive Probing of Raman Transitions, Chemical Engineering Journal, 429, 132260 (2022)</p><p>Keumrai Whang et al., Water-wettable Open Plasmonic Nanocavities for Ultrasensitive Molecular Detections in Multiple Phases, Nano Letters, 21 (14), pp 6194-6201 (2021)</p><p>Yonghee Shin et al., Microfluidic Multi-scale Homogeneous Mixing with Uniform Residence Time Distribution for Rapid Production of Various Metal Core–shell Nanoparticles, Advanced Functional Materials, 31, 202007856 (2021)</p><p>Jeehan Chang et al., "Generalized On-demand Production of Nanoparticle Monolayers on Arbitrary Solid Surfaces via Capillarity-Mediated Inverse Transfer, Nano Letters, 19 (3), pp 2074-2083 (2019)</p><p>Jin-Ho Lee et al., General and Programmable Synthesis of Hybrid Liposome/metal Nanoparticles, Science Advances, 2, e1601838 (2016)</p><p>Kihoon Kim et al., Interfacial liquid-state surface-enhanced Raman spectroscopy, Nature Communications, 4, 2182 (2013)</p>'
  where name_ko = '강태욱';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>서울대학교 공학사 (1995)</li><li>서울대학교 공학박사 (2001)</li></ul><h3>경력</h3><ul><li>Principal Investigator (Korea Research Institute of Chemical Technology, 2009 – 2014)</li><li>Team Leader (LG Chem Research Park, 2001 – 2009)</li></ul><h3>주요 논문</h3><p>Dong Hyeon Kim1,†, Hee Hwan Kim1,†, Juchan Kim1, Youngchang Byun2,*, and Kyoung-Su Ha1,*, Recovery of methyl methacrylate from waste poly (methyl methacrylate) pellets using a low-temperature plasma and zeolites, Chemical Engineering Journal, accepted, 2024. https://doi.org/10.1016/j.cej.2024.154438<br>Wonho Jung, Jinwon Lee*, and Kyoung-Su Ha*, A Combined Production Technology for Ethylene and Hydrogen with an Ethane Cracking Center and Dielectric Barrier Discharge Plasma Reactor, Chemical Engineering Journal 462 (2023) 142155. https://doi.org/10.1016/j.cej.2023.142155<br>Wonho Jung, Jinwon Lee*, Kyoung-Su Ha*, Ethylene Production Processes in a Carbon-Neutral Strategy, Energy Conversion and Management, 311 (2024) 118462. https://doi.org/10.1016/j.enconman.2024.118462<br>Juchan Kim, Jaekwon Jeoung, Jonghyun Jeon, Jip Kim, Young Sun Mok, Kyoung-Su Ha*, Effects of dielectric particles on non-oxidative coupling of methane in a dielectric barrier discharge plasma reactor, Chemical Engineering Journal 377 (2019) 119896-119908. https://doi.org/10.1016/j.cej.2018.09.057<br>Daegak Kim, Gyung-Ah Park, Jemi Lim, Kyoung-Su Ha*, Effects of spatially restricted Ni nanocrystals within ordered mesopores on the production of syngas, Chemical Engineering Journal 316 (2017) 1011-1025. https://doi.org/10.1016/j.cej.2017.02.014<br>Jongkook Hwang†, Geunjae Kwak†, Yun-Jo Lee, Yong Tae Kim, Inyoung Jeong, Seongseop Kim, Ki-Won Jun*, Kyoung-Su Ha*, Jinwoo Lee*, Direct confinement of Ru nanoparticles inside nanochannels of large pore mesoporous aluminosilicate for Fischer–Tropsch synthesis, Journal of Materials Chemistry A 3 (2015) 23725-23731. https://doi.org/10.1039/C5TA06184A<br>Kyoung-Su Ha*, Geunjae Kwak, Ki-Won Jun, Jongkook Hwang, Jinwoo Lee*, Ordered mesoporous carbon nanochannel reactors for high-performance Fischer–Tropsch synthesis, Chemical Communications 49 (2013) 5141-5143. https://doi.org/10.1039/C3CC00297G</p>'
  where name_ko = '하경수';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>Ph.D.,Georgia Institute of Technology(2011)</li></ul><h3>경력</h3><ul><li>Editorial Board Member (Journal of the Taiwan Institute of Chemical Engineers, 2023 – Present)</li><li>Visiting Scholar (University of California, Berkeley, 2022 – 2023)</li><li>Associate Editor (Korean Journal of Chemical Engineering, 2021 – Present)</li><li>Senior Research Scientist (Korea Institute of Science and Technology, 2012 – 2016)</li><li>Post-doc (Georgia Institute of Technology, 2011 – 2012)</li></ul><h3>주요 논문</h3><p>Ki Jin Nam, Hyun Jung Yu, Seungho Yu, Jeongho Seong, Seok-Jhin Kim, Ki Chul Kim, Jong Suk Lee, In situ synthesis of multivariate zeolitic imidazolate frameworks for C2H4/C2H6 kinetic separation, Small Methods 6 (2022) 2200772<br>(https://www.youtube.com/watch?v=fQzEhyBBV5w)<br>Heseong An, Kie Yong Cho, Seungho Yu, Ki Chul Kim, Ju Ho Shin, Ki Jin Nam, Jung Hoon Park, Jong Suk Lee, Triple-ligand zeolitic imidazolate frameworks for highly CO2 selective mixed matrix membranes, Chemical Engineering Journal 433 (2022) 133606<br>Heseong An, Kie Yong Cho, Qiang Lyu, Da-Shiuan Chiou, Ki Jin Nam, Dun-Yen Kang, Li-Chiang Lin, Jong Suk Lee, Facile defect engineering of zeolitic imidazolate frameworks towards enhanced C3H6/C3H8 separation performance, Advanced Functional Materials (2021) 2105577 (https://v.daum.net/v/20210907120016609)<br>Wonho Jung, Sunghyun Park, Kwang Soon Lee, Jae-Deok Jeon, Hyung Keun Lee, Jeong-Hoon Kim, Jong Suk Lee, Rapid thermal swing adsorption process in multi-beds scale with sensible heat recovery for continuous energy-efficient CO2 capture, Chemical Engineering Journal 392 (2020) 123656<br>Wansuk Choi, Changhoon Lee, Dahye Lee, Young June Won, Gi Wook Lee, Min Gyu Shin, Byoungjin Chun, Taek-Seung Kim, Hee-Deung Park, Hyun Wook Jung, Jong Suk Lee, Jung-Hyun Lee, Sharkskin-mimetic desalination membranes with ultralow biofouling, Journal of Materials Chemistry A 6 (2018) 23034-23045</p>'
  where name_ko = '이종석';

update faculty set
      research_ko = '<p class="text-lg font-semibold">Bioprocess engineering</p><p>DESIGN AND OPTIMIZATION OF BIOPROCESS WITH MULTI-SCALE FEATURES<br>Bioprocess has a multi-scale characteristic involving intracellular metabolic networks, cell-to-cell interactions, and spatiotemporal effects within bioreactors. These effects influence each other and eventually determine the performance of the process. Our research objective is to analyze these complicated behaviors in bioreactors with microbial cells and design and optimize novel systems based on the quantitative description of the process. We perform research, including monitoring critical metabolites in the cells, off-gas analysis, kinetic modeling, reactor design, and scale-down approach. Through these efforts, microbial fermentation, regarded as art, would be a core part of biotechnology.<br>BIOPROCESS DEVELOPMENT FOR C1 GAS CONVERSION FOR NET ZERO FUTURE<br>A carbon neutral society is a crucial agenda facing humanity today. Amid net-zero push, biological C1 gas conversion using biocatalysts could be a promising option for mitigating greenhouse gas emission and producing green chemicals. On the other hand, biological gas conversion is an interesting system in which there remain engineering issues to address. The poor mass transfer properties of gaseous substrates into culture broth limit carbon flux towards target products inside cells, thus restricting the productivity improvement. Also, the three-phase behavior of substrates (gas), culture medium (liquid), and cells (solids) makes mathematical analyses difficult. We are attempting to optimize biological gas conversion system using the abovementioned tools, ultimately contributing to a net-zero society establishment.</p>'
  where name_ko = '나정걸';

update faculty set
      research_ko = '<p class="text-lg font-semibold">Semiconductors and Display Materials.</p><p>Our research focus is on electronic materials such as quantum dots, semiconductor nanocrystals, organic semiconductors, and even electrolyte. We are interested in i) understanding physical properties of these materials including light emission/absorption characteristics, electrical/ionic transport characteristics, and electronic properties ii) developing processing methods for practical applications of these materials in semiconductor and display industry.</p><ul><li>High resolution patterning of quantum dots (QDs) – 양자점 초고해상도 패터닝 공정 개발</li><li>Electrical transport characteristics of semiconductor nanocrystals – 나노반도체의 전기전도 특성 이해</li><li>High resolution patterning of OLED materials – OLED 소재의 고해상도 패터닝 공정 개발</li><li>QD-LEDs and OLEDs – 양자점 발광소자 및 유기 발광소자</li><li>Electrochemistry and electrochemiluminescence 전기화학 및 전기화학발광</li><li>UV-crosslinkable materials - UV 경화형 소재</li></ul>',
      bio_ko = '<h3>학력</h3><ul><li>서울대학교 공학사 (2006)</li><li>University of Minnesota 공학박사(2011)</li></ul><h3>경력</h3><ul><li>Associate/assistant professor, Soongsil University, Korea (2012-2018)</li><li>Postdoctoral researcher, Seoul National University, Korea (2011)</li></ul><h3>주요 논문</h3><p>Direct Patterning of Colloidal Quantum Dots with Adaptable Dual-Ligand Surface - Nature Nanotechnology 2022</p><p>Nondestructive Photopatterning of Heavy-Metal-Free Quantum Dots - Advanced Materials 2022</p><p>Visco-Poroelastic Electrochemiluminescence Skin with Piezo-Ionic Effect - Advanced Materials 2021</p><p>High-resolution Pattering of Colloidal Quantum Dots via Non-destructive, Light-driven Ligand Crosslinking - Nature Communications 2020</p><p>Universal Three-Dimensional Crosslinker for All-Photopatterned Electronics - Nature Communications 2020</p><p>Light-emitting Devices Based on Electrochemiluminescence Gels - Advanced Functional Materials 2020</p><p>Universal Route to Impart Orthogonality to Polymer Semiconductors for Submicron Tandem Electronics - Advanced Materials 2019</p><p>Electrically Controllable Molecularization of Terahertz Meta-Atoms - Advanced Materials 2018</p><p>Lead-Free Perovskite Nanocrystals for Light-Emitting Devices – The Journal of Physical Chemistry Letters 2018</p><p>Light-Emitting Devices Based on Electrochemiluminescence: Comparison to Traditional Light-Emitting Electrochemical Cells – ACS Photonics 2018</p>'
  where name_ko = '강문성';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>KAIST 공학사 (2011)</li><li>KAIST 공학박사 (2017)</li></ul><h3>경력</h3><ul><li>박사후 연구원 (Dept. of Polymer Science and Engineering, University of Massachusetts Amherst, 2017-2020)</li><li>서강대학교 화공생명공학과 조교수 (2021-현재)</li></ul><h3>주요 논문</h3><p>Hyeong Jun Kim, Lindsay Paquin, Christopher W. Barney, Soonyong So, Baohong Chen, Zhigang Suo*, Alfred J. Crosby*, and Ryan C. Hayward* "Low-Voltage Reversible Electro-Adhesion of Ionoelastomer Junctions" Advanced Materials, 32 (2020) 2000600<br>Hyeong Jun Kim, Baohong Chen, Zhigang Suo*, and Ryan C. Hayward* "Ionoelastomer Junctions Between Polymer Networks of Fixed Anions and Cations" Science, 367 (2020) 773</p>'
  where name_ko = '김형준';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>UNIST 공학사 (2013)</li><li>UNIST 공학박사 (2018)</li></ul><h3>경력</h3><ul><li>2018-2020, 박사후 연구원(포항공과대학교)</li><li>2020-2022, 박사후 연구원(Pacific Northwest National Laboratory)</li></ul><h3>주요 논문</h3><p>Jieun Kang, Dong-Yeob Han, Sungho Kim, Jaegeon Ryu*, Soojin Park*, “Multiscale Polymeric Materials for Advanced Lithium Battery Applications”, Advanced Materials 34 (2022) 2203194.</p><p>Jaegeon Ryu†*, Dong-Yeob Han†, Dongki Hong, Soojin Park*, “A Polymeric Separator Membrane with Chemoresistance and High Li-ion Flux for High-Energy-Density Lithium Metal Batteries”, Energy Storage Materials 45 (2022) 941-951.</p><p>Jaegeon Ryu†, Taesoo Bok†, Se Hun Joo†, Seokkeun Yoo, Gyujin Song, Su Hwan Kim, Sungho Choi, Hu Young Jeong, Min Gyu Kim, Seok Ju Kang, Chongmin Wang*, Sang Kyu Kwak*, Soojin Park*, “Electrochemical Scissoring of Disordered Silicon-Carbon Composites for High-Performance Lithium Storage”, Energy Storage Materials 36 (2021) 139-146.</p><p>Jaegeon Ryu†, Sungho Kim†, Jimin Kim†, Sooham Park, Seungho Lee, Seokkeun Yoo, Jangbae Kim, Nam-Soon Choi, Ja-Hyoung Ryu*, Soojin Park*, “Room-Temperature Cross-Linkable Natural Polymer Binder for High-Rate and Stable Silicon Anode”, Advanced Functional Materials 30 (2020) 1908433.</p><p>Onur Buyukcakir†*, Jaegeon Ryu†, Se Hun Joo†, Jieun Kang, Recep Yuksel, Jiyun Lee, Yi Jiang, Sungho Choi, Sun Hwa Lee, Sang Kyu Kwak*, Soojin Park*, Rodney S. Ruoff*, “Lithium Accommodation in a Redox-Active Covalent Triazine Framework for High Areal Capacity and Fast-Charging Lithium-Ion Batteries”, Advanced Functional Materials 30 (2020) 2003761</p><p>Jaegeon Ryu†, Ji Hui Seo†, Gyujin Song, Keunho Choi, Dongki Hong, Chongmin Wang, Hosik Lee, Jun Hee Lee*, Soojin Park*, “Infinitesimal Sulfur Fusion Yields Quasi-Metallic Bulk Silicon for Stable and Fast Energy Storage”, Nature Communications 10 (2019) 2351.</p><p>Jaegeon Ryu†, Tianwu Chen†, Taesoo Bok†, Gyujin Song, Jiyoung Ma, Chihyun Hwang, Langli Luo, Hyun-Kon Song, Jaephil Cho, Chongmin Wang*, Sulin Zhang*, Soojin Park*, “Mechanical Mismatch-Driven Rippling in Carbon-Coated Silicon Sheets for Stress-Resilient Battery Anodes”, Nature Communications 9 (2018) 2924.</p>'
  where name_ko = '류재건';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>KAIST 이학사 (2007)</li><li>KAIST 이학박사(2012)</li></ul><h3>경력</h3><ul><li>책임연구원 (한국화학연구원, 2014-2022)</li><li>겸직교수 (포항공대, 2020-2022)</li><li>부교수 (과학기술연합대학원대학교, 2016-2022)</li><li>연구원 (SK이노베이션, 2012-2014)</li></ul><h3>주요 논문</h3><p>Sungbin Ju, Giyoung Shin, Minkyung Lee, Jun Mo Koo, Hyeonyeol Jeon, Yong Sik Ok, Dong Soo Hwang, Sung Yeon Hwang, Dongyeop X Oh, Jeyoung Park, “Biodegradable chito-beads replacing non-biodegradable microplastics for cosmetics”, Green Chemistry 23 (2021) 6953-6965.</p><p>Hyeri Kim, Hyeonyeol Jeon, Giyoung Shin, Minkyung Lee, Jonggeon Jegal, Sung Yeon Hwang, Dongyeop X Oh, Jun Mo Koo, Youngho Eom, Jeyoung Park, “Biodegradable nanocomposite of poly (ester-co-carbonate) and cellulose nanocrystals for tough tear-resistant disposable bags”, Green Chemistry 23 (2021) 2293-2299.</p><p>Seul-A Park, Youngho Eom, Hyeonyeol Jeon, Jun Mo Koo, Eun Seong Lee, Jonggeon Jegal, Sung Yeon Hwang, Dongyeop X Oh, Jeyoung Park, “Preparation of synergistically reinforced transparent bio-polycarbonate nanocomposites with highly dispersed cellulose nanocrystals”, Green Chemistry 21 (2019) 5212-5221.</p><p>Seul-A Park, Hyeonyeol Jeon, Hyungjun Kim, Sung-Ho Shin, Seunghwan Choy, Dong Soo Hwang, Jun Mo Koo, Jonggeon Jegal, Sung Yeon Hwang, Jeyoung Park, Dongyeop X Oh, “Sustainable and recyclable super engineering thermoplastic from biorenewable monomer”, Nature Communications 10 (2019) 2601.</p><p>Seon‐Mi Kim, Hyeonyeol Jeon, Sung‐Ho Shin, Seul‐A Park, Jonggeon Jegal, Sung Yeon Hwang, Dongyeop X Oh, Jeyoung Park, “Superior toughness and fast self‐healing at room temperature engineered by transparent elastomers”, Advanced Materials 30 (2018) 1705145.</p>'
  where name_ko = '박제영';

update faculty set
      bio_ko = '<h3>학력</h3><ul><li>서울대학교 공학사 (2014)</li><li>서울대학교 공학박사 (2020)</li></ul><h3>경력</h3><ul><li>2020-2022, 박사후 연구원(서울대학교)</li><li>2023-2025, 박사후 연구원(Northwestern University)</li></ul><h3>주요 논문</h3><p>“Durable and Active Nitrogen-Coordinated Iron Single-Atom Catalyst for Proton Exchange Membrane Fuel Cells Through Carbon Encapsulation” Advanced Energy Materials 14 (2024) 2400565.<br>“Electrochemically generated electrophilic peroxo species accelerates alkaline oxygen evolution reaction”, Joule 7 (2023), 1902-1919.<br>“Supramolecular tuning of supported metal phthalocyanine catalysts for hydrogen peroxide electrosynthesis”, Nature Catalysis 6 (2023) 234-243.<br>“Carbon Shell on Active Nanocatalyst for Stable Electrocatalysis”, Accounts of Chemical Research 55 (2022) 1278-1289.<br>“Atomic-level Tuning of Co-N-C Catalyst for High-Performance Electrochemical H2O2 Production”, Nature Materials 19 (2020) 436-44.</p>'
  where name_ko = '신희종';

-- ── 연구분야 키워드 (상세 페이지 칩) ──
-- 옛 홈페이지에는 키워드가 없거나 한 토막('Organic')만 있던 분이 많아 각자 연구 소개 글에서 뽑아 3~4개로 맞췄다.
-- 교수님이 직접 고칠 내용이므로 /adm 교수진 화면에서 언제든 바꿀 수 있다.
update faculty set keywords = 'Perovskite Solar Cells, Organic Photodiode & Photodetector, Interface Engineering, Flexible Optoelectronics' where name_ko = '오세용';
update faculty set keywords = 'Brainformatics, Computational Neuroscience, Associative Memory, Behavioral Economics' where name_ko = '최진훈';
update faculty set keywords = 'Biochemical Engineering, Metabolic Engineering, C1 Gas Bioconversion, Microbial Biocatalysis' where name_ko = '이진원';
update faculty set keywords = 'Biosensor Platform, Point-of-Care Diagnostics, Microfluidics, Nano-bio Materials' where name_ko = '오병근';
update faculty set keywords = 'Nanoplasmonics, Nanophotonics, Biophotonics, Optofluidic Diagnostics' where name_ko = '강태욱';
update faculty set keywords = 'Electrochemical Engineering, Hydrogen & Electrolyzers, Fuel Cells, Mathematical Modeling' where name_ko = '조현석';
update faculty set keywords = 'Functional Nanomedicine, Gene Delivery, mRNA Vaccine, Cancer Immunotherapy' where name_ko = '김현철';
update faculty set keywords = 'Organic/Inorganic Hybrid Electronics, Optoelectronic Devices, Green Process, Polymer Electrolytes' where name_ko = '김충익';
update faculty set keywords = 'Heterogeneous Catalysis, Compact Reactor Design, Reaction Kinetics, Carbon Neutral Process' where name_ko = '하경수';
update faculty set keywords = 'Membranes, Sorbents & Barriers, Mixed Matrix Membranes, Gas Separation' where name_ko = '이종석';
update faculty set keywords = 'Bioprocess Engineering, Bioreactor Design, Kinetic Modeling, Microbial Fermentation' where name_ko = '나정걸';
update faculty set keywords = 'Quantum Dots, QD-LED & OLED, High-resolution Patterning, Display Materials' where name_ko = '강문성';
update faculty set keywords = 'Charged Polymers, Polyelectrolytes, Ionotronics, Soft Functional Devices' where name_ko = '김형준';
update faculty set keywords = 'Energy Storage Materials & Systems, Rechargeable Batteries, Electrode Materials, Polymeric Binders' where name_ko = '류재건';
update faculty set keywords = 'Sustainable Plastics, Biodegradable Polymers, Polymerization, Carbon Neutrality' where name_ko = '박제영';
update faculty set keywords = 'Electrochemistry, Electrocatalysis, Energy Conversion & Storage, in situ Analysis' where name_ko = '신희종';
update faculty set keywords = 'Genome Engineering, Cell Engineering, Mitochondrial Biology, Genome Editing Therapeutics' where name_ko = '이성현';
update faculty set keywords = 'Biochemical Engineering, Nanobiotechnology, Biorobotics' where name_ko = '최정우';
