/** 학부과정 > 전공소개 (이승엽 교수님 원고 + Physical AI 소개자료 기반).
 * 4개 기초 분야를 학과 공식 순서(설계 → 열유체 → 제어 → 생산)로, 각 분야의 고유 학문 영역과
 * 폭넓은 산업 응용을 중심으로 균형 있게 서술하고 Physical AI는 최신 트렌드와의 연결로 언급한다. */
export const majorFields = [
  { id: 'design', ko: '설계 · 역학', en: 'Design & Mechanics', tagKo: '구조와 시스템 설계의 근간', tagEn: 'The foundation of structural and system design',
    summaryKo: '구조설계, 응력·진동 해석, 유한요소해석, 최적설계',
    bodyKo: '설계·역학 분야는 기계 부품과 구조물에 작용하는 힘·응력·변형·진동을 해석하고 이를 견디는 구조를 만드는, 기계공학의 근간이 되는 분야입니다. 고체역학, 동역학, 유한요소해석, 최적설계를 바탕으로 자동차, 항공우주, 플랜트, 정밀기계, 의료기기 등 모든 산업에서 제품의 강성·경량화·내구성·신뢰성을 확보합니다. 경량화와 강성을 동시에 달성하는 위상 최적설계, 충격과 피로에 대한 신뢰성 설계, 메커니즘의 운동학·동역학 해석이 이 분야의 핵심 역량이며, 최근에는 휴머노이드 로봇과 Physical AI 하드웨어의 골격과 구동 구조를 설계하는 영역으로도 역할이 확장되고 있습니다.',
    bodyEn: 'Design and mechanics is the backbone of mechanical engineering: analyzing the forces, stresses, deformation and vibration acting on parts and structures, and designing structures that withstand them. Built on solid mechanics, dynamics, finite element analysis and optimal design, it secures stiffness, light weight, durability and reliability across every industry — automotive, aerospace, plants, precision machinery and medical devices. Topology optimization for simultaneous lightness and stiffness, reliability design against impact and fatigue, and kinematic and dynamic analysis of mechanisms are its core, and its role now extends to the skeletons and drive structures of humanoid robots and Physical AI hardware.',
    courses: ['고체역학', '제품설계기초', '재료거동학', '부품설계', '유한요소해석', '설계방법론', '최적설계 및 실습'],
    coursesEn: ['Solid Mechanics', 'Fundamentals of Product Design', 'Mechanical Behavior of Materials', 'Machine Component Design', 'Finite Element Analysis', 'Design Methodology', 'Optimal Design and Practice'] },
  { id: 'thermal', ko: '열 · 유체', en: 'Thermal & Fluids', tagKo: '에너지와 흐름을 다루는 과학', tagEn: 'The science of energy and flow',
    summaryKo: '열전달, 유체역학, 에너지 변환, 냉각·공조 시스템',
    bodyKo: '열·유체 분야는 에너지가 변환되고 유체가 흐르며 열이 전달되는 원리를 탐구합니다. 발전과 신재생에너지, 자동차·항공 추진기관, 냉동·공기조화, 연료전지와 이차전지 열관리 등 에너지가 관여하는 모든 산업의 핵심 기술이며, 반도체 공정과 AI 데이터센터 냉각처럼 첨단 산업의 성능 한계를 결정짓는 분야이기도 합니다. 전산유체역학(CFD)과 열전달 해석으로 눈에 보이지 않는 흐름을 예측하고 설계하며, 고출력 모터·배터리·전력 반도체의 발열 관리를 통해 로봇과 Physical AI 시스템이 장시간 안정적으로 작동하기 위한 기반 기술도 제공합니다.',
    bodyEn: 'Thermal-fluids engineering explores how energy is converted, how fluids flow and how heat is transferred. It is the core technology of every energy-related industry — power generation and renewables, automotive and aerospace propulsion, refrigeration and air conditioning, fuel-cell and battery thermal management — and it sets the performance limits of advanced industries such as semiconductor processing and AI data-center cooling. With computational fluid dynamics and heat-transfer analysis it predicts and designs flows invisible to the eye, and by managing the heat of high-power motors, batteries and power semiconductors it also underpins the long, stable operation of robots and Physical AI systems.',
    courses: ['열역학I', '유체역학I', '자동차동력공학', '열전달', '냉동 및 공기조화', '신재생에너지공학개론', '전산유체역학', '연료전지개론'],
    coursesEn: ['Thermodynamics I', 'Fluid Mechanics I', 'Automotive Powertrain Engineering', 'Heat Transfer', 'Refrigeration and Air Conditioning', 'Introduction to Renewable Energy Engineering', 'Computational Fluid Dynamics', 'Introduction to Fuel Cells'] },
  { id: 'control', ko: '제어 · 진동 · 로보틱스', en: 'Control, Vibration & Robotics', tagKo: '움직임을 지능으로 완성하는 분야', tagEn: 'Completing motion with intelligence',
    summaryKo: '정밀제어, 진동 해석, 메카트로닉스, 로봇, Physical AI',
    bodyKo: '자동차, 항공기, 로봇 및 정밀 기계류의 힘과 진동을 해석하고, 원하는 목표를 이루기 위한 설계와 능동 제어를 연구합니다. 고속·고정밀 제어와 메카트로닉스 기술은 공작기계와 생산 설비부터 자율주행, 드론, 의료 로봇까지 폭넓은 산업에서 활용됩니다. 미래 산업의 화두인 로봇 및 Physical AI와 직결되는 분야로, 다양한 로봇 설계·제작과 LLM AI를 기계장치에 연결하여 지능화하는 연구를 새롭게 시작하고 있으며, 바이오 응용으로 생체 모방 로봇·센서·액츄에이터와 의공학 응용 바이오 시스템을 연구합니다.',
    bodyEn: 'This field analyzes forces and vibration in vehicles, aircraft, robots and precision machinery, and develops design and active control to reach a desired goal. High-speed precision control and mechatronics serve industries from machine tools and production equipment to autonomous driving, drones and medical robots. Directly connected to robotics and Physical AI, new research links LLM-based AI to machines for intelligent operation and develops biomimetic robots, sensors and actuators for biomedical systems.',
    courses: ['동역학', '진동학', '자동제어', '디지털제어시스템', '메카트로닉스', '고급동역학', '로봇설계 및 제어'],
    coursesEn: ['Dynamics', 'Mechanical Vibrations', 'Automatic Control', 'Digital Control Systems', 'Mechatronics', 'Advanced Dynamics', 'Robot Design and Control'] },
  { id: 'manufacturing', ko: '생산 · 제조', en: 'Manufacturing', tagKo: '아이디어를 실체로 만드는 기술', tagEn: 'Turning ideas into physical reality',
    summaryKo: '재료, 정밀가공, 3D 프린팅, 반도체·MEMS, 스마트 제조',
    bodyKo: '생산·제조 분야는 재료의 선정과 개발, 정밀 가공, 적층 제조(3D 프린팅), 미세 조립을 통해 디지털 설계를 물리적 실체로 전환합니다. 초정밀·레이저 가공, 반도체·MEMS 공정, 복합재료 같은 첨단 제조 기술은 자동차, 전자, 바이오, 에너지 등 제조업 전반의 경쟁력을 결정하며, 최근에는 AI 기반 공정 자동화와 스마트 제조로 영역을 넓히고 있습니다. 소프트 로봇용 유연 소재와 경량 고강도 복합재, 생체적합성 재료의 개발부터 마이크로미터 정밀도의 가공·조립까지, 설계된 제품이 시제품을 넘어 산업 현장에서 양산되도록 뒷받침하는 것이 이 분야의 역할입니다.',
    bodyEn: 'Manufacturing turns digital designs into physical reality through material selection and development, precision machining, additive manufacturing (3D printing) and micro-assembly. Advanced manufacturing technologies — ultra-precision and laser machining, semiconductor and MEMS processes, composite materials — decide the competitiveness of the automotive, electronics, bio and energy industries, and the field is now expanding into AI-driven process automation and smart manufacturing. From flexible materials for soft robots, lightweight high-strength composites and biocompatible materials to micrometer-precision fabrication and assembly, it carries designs beyond the prototype into industrial production.',
    courses: ['기계제작실습', '기계재료기초', '생산공정', 'CAD', '복합재료입문', '마이크로나노기계공학', '공정설계의 CAE', '반도체공학', 'MEMS 설계제작'],
    coursesEn: ['Manufacturing Practice', 'Fundamentals of Engineering Materials', 'Manufacturing Processes', 'CAD', 'Introduction to Composite Materials', 'Micro/Nano Chemical and Biomolecular Engineering', 'CAE for Process Design', 'Semiconductor Engineering', 'MEMS Design and Fabrication'] },
];
export const introCourse = {
  ko: { name: '지능형 기계설계생산 입문', desc: '기계공학의 기초 역학지식을 기반으로 지능형 기계시스템의 이론·설계·제작 과정을 직접 체험하도록 구성된 교과목입니다. 프로젝트 기반 문제 해결 활동을 통해 물리, 재료, 전자, 정보과학, AI 등 다양한 학문이 융합된 현대 기계공학의 특성을 이해하고, 지능형 설계와 스마트 제조의 핵심적 역할을 수행하는 기계공학의 본질을 경험합니다. C·MATLAB·Arduino 등 기초 도구를 익히고 CAD/3D프린팅 실습, 센서-모터 기반 메카트로닉스 제작, 팀 프로젝트를 통해 창의적 설계 역량과 공학적 사고능력을 기릅니다.' },
  en: { name: 'Introduction to Intelligent Mechanical Design & Manufacturing', desc: 'A hands-on course in which students experience the theory, design and fabrication of intelligent mechanical systems through project-based problem solving — learning C, MATLAB and Arduino, CAD/3D printing, sensor-motor mechatronics and team projects.' },
};
export const introSlides = Array.from({ length: 15 }, (_, i) => `/images/intro/physical-ai-p${String(i + 1).padStart(2, '0')}.jpg`);
